# Generated by Django 2.1 on 2018-08-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.CharField(max_length=250),
        ),
    ]
